name: Cleanup Artifacts

permissions: {}

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: repo-*
          failOnError: false
