name: Deploy Website Build

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      default_path:
        type: string
        default: /en/index.html
    secrets:
      PROD_MINIO_KEY_ID:
      PROD_MINIO_SECRET_KEY:

jobs:
  minio_production:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    environment:
      name: ${{ inputs.environment }}
      url: https://${{ vars.PROD_MINIO_BUCKET }}.${{ vars.PROD_MINIO_HOSTNAME }}${{ inputs.default_path }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: site-build-*
          merge-multiple: true

      - run: |
          for file in *.tar.gz; do tar -zxf "$file"; done
          ls -la site/

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: "site/"
          AWS_S3_BUCKET: ${{ vars.PROD_MINIO_BUCKET }}
          AWS_S3_ENDPOINT: https://${{ vars.PROD_MINIO_HOSTNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_MINIO_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_MINIO_SECRET_KEY }}
