# Copyright (c) 2024 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: Download Repository

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      privileged:
        type: boolean
        default: true
    secrets:
      ACTIONS_SSH_KEY:
        required: false

jobs:
  download:
    if: ${{ inputs.privileged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "privacyguides/${{ inputs.repo }}"
          path: repo-${{ inputs.repo }}
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: repo-${{ inputs.repo }}
          path: repo-${{ inputs.repo }}
          retention-days: 1
          include-hidden-files: true

  download_unprivileged:
    if: ${{ !inputs.privileged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "privacyguides/${{ inputs.repo }}"
          path: repo-${{ inputs.repo }}

      - uses: actions/upload-artifact@v4
        with:
          name: repo-${{ inputs.repo }}
          path: repo-${{ inputs.repo }}
          retention-days: 1
          include-hidden-files: true
